[application]

[web.app]

# HTML title tag content
title = "scorecounter"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["/assets/main.css"]

# Additional JavaScript files
script = ["/assets/sw-register.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = ["/assets/sw-register.js"]
